#!/bin/sh /etc/rc.common

START=99

SERVICE_DAEMONIZE=1
SERVICE_WRITE_PID=1

EXTRA_COMMANDS="status"
EXTRA_HELP="        status  Returns the status of the daemon"

start() {
        cd /etc/xmppconn
        service_start /usr/bin/xmppconn
}

stop() {
        service_stop /usr/bin/xmppconn
        rm -f /tmp/run/xmppconn.pid
}

status() {
        if [ -f /tmp/run/xmppconn.pid ];
        then
                echo "Running"
        else
                echo "Stopped"
        fi
}

